### ISSUE TITLE
Error not announced when making this syntax error

### ISSUE THREAD

**Issue by dukc** [bridgedotnet/CLI#21]
This class compiles just fine

```
public class LetterInvalid : Exception
{   public LetterInvalid(char letter) : base()
    {   this.letter = letter;
    }
    public char letter;
    public int decorationIndex;
}
```

However, if I make the error of using two colons to inherit the constructor:

```
public class LetterInvalid : Exception
{   public LetterInvalid(char letter) :: base()
    {   this.letter = letter;
    }
    public char letter;
    public int decorationIndex;
}
```

...the CLI won't announce what went wrong. Instead: `Bridge.NET Compiler error: exception level: 0 - Syötemerkkijonon muoto ei ollut kelvollinen.` and nothing else, besides stack trace:
```
Stack trace:
   kohteessa System.Text.StringBuilder.FormatError()
   kohteessa System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   kohteessa System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   kohteessa System.String.Format(String format, Object[] args)
   kohteessa Bridge.Translator.TranslatorException.Throw(String format, Object[] args)
   kohteessa Bridge.Translator.Translator.BuildAssembly()
   kohteessa Bridge.Translator.Translator.Translate()
   kohteessa CallSite.Target(Closure , CallSite , Object )
   kohteessa System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   kohteessa Bridge.CLI.Program.Main(String[] args)
```

("Syötemerkkijonon muoto ei ollut kelvollinen" means "Input string was not of valid form")

In fact, there are many syntax errors that cause the compiler to halt like that, but only recently I decided to start to report them, so here is one case.

**Comment by fabriciomurta** [comment]
Fixed! The fix was done within Bridge's Translator, (so, not directly to Bridge CLI) and will be available next release.

EDIT: At this time, the next Bridge scheduled release would be 17.3.0.
