### ISSUE TITLE
Error: Minimum required version of Bridge compiler is 17.3.0. Your version: 17.2.0.

### ISSUE THREAD

**Issue by FlowIT-JIT** [bridgedotnet/CLI#23]
No matter what command I execute with bridge - even just `bridge <enter>`, it get the following error:
Minimum required version of Bridge compiler is 17.3.0. Your version: 17.2.0.

I installed the CLI tool from https://bridge.net/download/
and installed it on Windows Server 2012 R2 Standard.

The VS 2017 extension works fine.

**Comment by FlowIT-JIT** [comment]
Naturally I tried following the instructions in the readme: https://github.com/bridgedotnet/CLI#bridge-cli

**Comment by geoffreymcgill** [comment]
Hi @FlowIT-JIT – Thanks for the report. We are investigating.

**Comment by fabriciomurta** [comment]
Did you try upgrading the NuGet packages in your project either via the NuGet commandline or a VS IDE's NuGet package manager?

Bridge CLI has the initial subsystem to install NuGet packages, but it does not implement an `upgrade` automatically.

**Comment by fabriciomurta** [comment]
I'm assuming your issue is with the lack of upgrade, let us know if I'm wrong and we'll reopen this; so that we already have issue #19 tracking this. You're welcome to share your thoughts there too.
