### ISSUE TITLE
Deck.NET compiles significantly faster than `bridge build`

### ISSUE THREAD

**Issue by mrmiguu** [bridgedotnet/CLI#31]
1\~2 seconds is all Deck.NET takes to compile the same HelloWorld program that the Bridge.NET CLI generates with `bridge new`, but Bridge.NET takes 4~5 seconds. That's a 250%\~400% slowdown.

https://deck.net/8863ecb5e31cf900c46c25aab17f6234

**Comment by geoffreymcgill** [comment]
See bridgedotnet/Bridge#4075
