### ISSUE TITLE
The "new" command breaks with strange error message if `packages` folder is present

### ISSUE THREAD

**Issue by fabriciomurta** [bridgedotnet/CLI#4]
If `bridge new` is run and then run again, a unexpected error is raised:

```
$ ./bridge.exe new
Minimum required version of Bridge compiler is 16.4.2. Your version: 16.4.1
```

![image](https://user-images.githubusercontent.com/10730372/32402898-10d35944-c115-11e7-8443-268ae4d5f450.png)

**Comment by vladsch** [comment]
It is expected result till 16.4.2 will be released

**Comment by geoffreymcgill** [comment]
Looks like this is fixed.
