### ISSUE TITLE
remove package <name> command is case-sensitive

### ISSUE THREAD

**Issue by geoffreymcgill** [bridgedotnet/CLI#6]
Removing a package by name should be case-insensitive.

```
// add success
bridge add package bridge.html5

// fail
bridge remove package bridge.html5

// success
bridge remove package Bridge.Html5
```

**Comment by fabriciomurta** [comment]
Commented on related commits pointing here. The issue has been fixed first directly in `master`, then merged down to `dev` then its side effect fixed in `dev`, before closing the 16.7.0 release. So this is part of Bridge 16.7.0.
